[package]
name = "orca_whirlpools_client_integration_anchor_v0_32"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
anchor-lang = { version = "~0.32.1" }
orca_whirlpools_client = { path = "../../../client", features = ["anchor"] }