[package]
name = "whirlpool"
version = "0.3.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "=0.29.0" }
anchor-spl = { version = "=0.29.0", features = ["metadata", "memo"] }
spl-token = { version = "=4.0.1", features = ["no-entrypoint"] }
spl-transfer-hook-interface = { version = "=0.5.0" }
solana-program = { version = "=1.17.22" }
uint = { version = "=0.9.5", default-features = false }
arrayref = { version = "=0.3.8" }
borsh09 = { package = "borsh", version = "=0.9.3" }
solana-security-txt = { version = "=1.1.1" }
bytemuck = { version = "=1.16.3", features = ["derive", "min_const_generics"] }

[dev-dependencies]
proptest = "=1.5.0"
serde = "=1.0.208"
serde_json = "=1.0.124"

[dev-dependencies.serde_with]
version = "=2.3.3"
features = ["json"]
