[package]
name = "whirlpool"
version = "0.3.2"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "=0.30.1" }
anchor-spl = { version = "=0.29.0", features = ["metadata", "memo"] }
spl-token = { version = "=4.0.1", features = ["no-entrypoint"] }
spl-transfer-hook-interface = { version = "=0.5.0" }
spl-token-metadata-interface = { version = "=0.2.0" }
solana-program = { version = "=1.17.22" }
uint = { version = "=0.10.0", default-features = false }
arrayref = { version = "=0.3.9" }
borsh09 = { package = "borsh", version = "=0.9.3" }
solana-security-txt = { version = "=1.1.1" }
bytemuck = { version = "=1.21.0", features = ["derive", "min_const_generics"] }

[dev-dependencies]
proptest = "=1.6.0"
serde = "=1.0.216"
serde_json = "=1.0.134"

[dev-dependencies.serde_with]
version = "=3.12.0"
features = ["json"]
