[package]
name = "whirlpool"
version = "0.3.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "whirlpool"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29"
anchor-spl = {version = "0.30", features = ["metadata", "memo"]}
spl-token = {version = "4", features = ["no-entrypoint"]}
spl-transfer-hook-interface = "0.5.0"
solana-program = "1.17"
thiserror = "1.0"
uint = {version = "0.9.1", default-features = false}
borsh09 = {package = "borsh", version = "0.9.1"}
arrayref = "0.3.7"
bytemuck = "1.14.3"
solana-security-txt = { version = "=1.1.1" }

[dev-dependencies]
proptest = "1.0"
serde = "1.0.117"
serde_json = "1.0.59"

[dev-dependencies.serde_with]
version = "1.12.0"
features = ["json"]
