[package]
name = "orca_whirlpools_core"
version = "0.1.0"
description = "Orca's core rust package."
documentation = "https://orca-so.github.io/whirlpools/"
homepage = "https://orca.so"
repository = "https://github.com/orca-so/whirlpools"
license = "Apache-2.0"
keywords = ["solana", "crypto", "defi", "dex", "amm"]
edition = "2021"

[features]
default = ["floats", "wasm"]
wasm = ["dep:serde-big-array", "dep:orca_whirlpools_macros"]
floats = ["dep:libm"]

[dependencies]
ethnum = { version = "^1.5" }
libm = { version = "^0.2", optional = true }
orca_whirlpools_macros = { path = "../macros", optional = true }
wasm-bindgen = { version = "^0.2" }
serde = { version = "^1", features = ["derive"] }
serde-big-array = { version = "^0.5", optional = true }
serde-wasm-bindgen = { version = "^0.6" }
tsify = { version = "^0.4", features = ["js"]}

[dev-dependencies]
print-no-std = { version = "^0.1"}
approx = { version = "^0.3" }
