[package]
name = "orca_whirlpools_client"
version = "0.1.0"
edition = "2021"

[features]
anchor = ["dep:anchor-lang"]
anchor-idl-build = []
test-sbf = []
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
anchor-lang = { version = "^0.30.0", optional = true }
borsh = { version = "^1.5.1" }
num-derive = { version = "^0.4.2" }
num-traits = { version = "^0.2.19" }
solana-program = { version = "^1.18.21" }
thiserror = { version = "^1.0.63" }
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
