[package]
name = "orca_whirlpools_client"
version = "0.1.0"
description = "Rust client to interact with Orca's on-chain Whirlpool program."
include = ["src/*"]
documentation = "https://orca-so.github.io/whirlpools/"
homepage = "https://orca.so"
repository = "https://github.com/orca-so/whirlpools"
license = "Apache-2.0"
keywords = ["solana", "crypto", "defi", "dex", "amm"]
authors = ["team@orca.so"]
edition = "2021"

[features]
default = []
anchor = ["dep:anchor-lang"]
anchor-idl-build = []
test-sbf = []
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
anchor-lang = { version = "^0.30.0", optional = true }
borsh = { version = "^0.10.3" }
num-derive = { version = "^0.4.2" }
num-traits = { version = "^0.2.19" }
solana-program = { version = "^1.18.21" }
thiserror = { version = "^1.0.64" }
serde = { version = "^1.0.210", features = ["derive"], optional = true }
serde_with = { version = "^3.10.0", optional = true }
