[package]
name = "orca_whirlpools_client"
version = "0.1.0"
description = "Rust client to interact with Orca's on-chain Whirlpool program."
include = ["src/*"]
documentation = "https://orca-so.github.io/whirlpools/"
homepage = "https://orca.so"
repository = "https://github.com/orca-so/whirlpools"
license = "Apache-2.0"
keywords = ["solana", "crypto", "defi", "dex", "amm"]
authors = ["team@orca.so"]
edition = "2021"

[features]
default = ["core-types"]
anchor = ["dep:anchor-lang"]
anchor-idl-build = []
test-sbf = []
core-types = ["dep:orca_whirlpools_core"]
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
anchor-lang = { version = "^0", optional = true }
borsh = { version = "^0" }
num-derive = { version = "^0" }
num-traits = { version = "^0" }
orca_whirlpools_core = { path = "../core", optional = true }
serde = { version = "^1", features = ["derive"], optional = true }
serde_with = { version = "^3", optional = true }
solana-program = { version = "^2" }
thiserror = { version = "^2" }
