[package]
name = "orca_whirlpools"
version = "0.1.0"
description = "Orca's high-level rust sdk to interact with Orca's on-chain Whirlpool program."
documentation = "https://orca-so.github.io/whirlpools/"
homepage = "https://orca.so"
repository = "https://github.com/orca-so/whirlpools"
license = "Apache-2.0"
keywords =["orca_so", "orca", "solana", "rust", "sdk", "crypto", "defi", "dex", "amm"]
edition = "2021"

[dependencies]
orca_whirlpools_client = { path = "../client" }
