[package]
name = "orca_whirlpools_client_integration_anchor_v0_31"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
anchor-lang = { version = "~0.31.0" }
solana-program = { version = "~2.1.0" }
orca_whirlpools_client = { path = "../../../client", features = ["anchor"] }
