[package]
name = "orca_whirlpools_core_integration_libm_v0_1"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
libm = { version = "~0.1.4" }
orca_whirlpools_core = { path = "../../../core" }
