[package]
name = "orca_whirlpools_client_integration_anchor_v0_28"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
anchor-lang = { version = "~0.28.0" }
orca_whirlpools_client = { path = "../../../client", features = ["anchor"] }
