[package]
name = "orca_whirlpools_core_integration_ethnum_v1_4"
edition = "2021"

[lib]
path = "../../lib.rs"

[dependencies]
ethnum = { version = "~1.4.0" }
orca_whirlpools_core = { path = "../../../core" }
